"""Add membership history table

Revision ID: abc123
Revises: 4875f19211ae
Create Date: 2025-07-30 01:54:50.068823

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f89a1b2c3d4"
down_revision: Union[str, None] = "4875f19211ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "membershiphistorymodel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reset_date", sa.DateTime(), nullable=False),
        sa.Column("was_full_member", sa.Boolean(), nullable=True),
        sa.Column("had_paid_dues", sa.Boolean(), nullable=True),
        sa.Column("original_join_date", sa.Integer(), nullable=True),
        sa.Column("could_vote", sa.Boolean(), nullable=True),
        sa.Column("reset_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_name_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("surname_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("discord_username_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usermodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("usermodel", sa.Column("renewal", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("membershiphistorymodel")
    op.drop_column("usermodel", "renewal")
    # ### end Alembic commands ###
