"""Add non_ucf_terms_agreement field

Revision ID: 914bb7ce5299
Revises: c461357e905b
Create Date: 2025-10-09 11:14:31.135157

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "914bb7ce5299"
down_revision: Union[str, None] = "c461357e905b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usermodel", sa.Column("non_ucf_terms_agreement", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usermodel", "non_ucf_terms_agreement")
    # ### end Alembic commands ###
