"""Add admin compliance training fields

Revision ID: b3d6e9a2f150
Revises: a7f2c9d41b83
Create Date: 2026-09-23 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3d6e9a2f150"
down_revision: Union[str, None] = "a7f2c9d41b83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usermodel", sa.Column("admin_compliance_reporter_ack", sa.Boolean(), nullable=True))
    op.add_column("usermodel", sa.Column("admin_compliance_government_ack", sa.Boolean(), nullable=True))
    op.add_column("usermodel", sa.Column("admin_compliance_first_amendment_ack", sa.Boolean(), nullable=True))
    op.add_column("usermodel", sa.Column("admin_compliance_sponsor_ack", sa.Boolean(), nullable=True))
    op.add_column("usermodel", sa.Column("admin_compliance_peer_ack", sa.Boolean(), nullable=True))
    op.add_column("usermodel", sa.Column("admin_compliance_signtime", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usermodel", "admin_compliance_signtime")
    op.drop_column("usermodel", "admin_compliance_peer_ack")
    op.drop_column("usermodel", "admin_compliance_sponsor_ack")
    op.drop_column("usermodel", "admin_compliance_first_amendment_ack")
    op.drop_column("usermodel", "admin_compliance_government_ack")
    op.drop_column("usermodel", "admin_compliance_reporter_ack")
    # ### end Alembic commands ###
