repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff-format
      - id: ruff
        exclude: ^tests/codegen/snapshots/python/
        args: [--select, I, "--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: '^docs/.*\.mdx?$'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/semgrep/semgrep
    rev: 'v1.65.0'
    hooks:
      - id: semgrep
        # See https://semgrep.dev/explore to select a ruleset and copy its URL
        args: ['--error', '--skip-unknown-extensions']
