version: '3'
services:
  fastapi:
    build: .
    ports:
      - 8000:8000
    # environment:
      # - REDIS_HOST=redis
    volumes:
      - ./config.yml:/app/config/options.yml

  redis:
    image: redis:7.2
