services:
  fastapi:
    image: ghcr.io/hackucf/onboardlite:latest
    environment:
      - BWS_ACCESS_TOKEN={$BWS_ACCESS_TOKEN}
    ports:
      - 8000:8000
    volumes:
      - ./config/options.yml:/src/config/options.yml
      - ./database/:/data/
