name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build . --target prod -t onboardlite

      - name: Verify Docker image
        run: docker run -e ONBOARD_ENV=dev --rm onboardlite echo "Docker image built successfully!"
