name: Build Docker Image Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build . --target prod -t onboardlite

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name onboardlite_container onboardlite

      - name: sleep 10 seconds
        run: sleep 10

      - name: Wait for container to be ready
        run: |
          for i in {1..30}; do
            if curl -s -v http://localhost:8000/; then
              exit 0
            fi
            sleep 1
          done
          docker logs onboardlite_container
          exit 1

      - name: Verify homepage
        run: curl -f -v http://localhost:8000/

      - name: Stop and remove Docker container
        run: docker stop onboardlite_container && docker rm onboardlite_container