name: pre-commit

on:
  pull_request:
  push:
    branches: [dev, main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: echo "SKIP=semgrep" >> $GITHUB_ENV
      - run: uv run pre-commit --show-diff-on-failure --color=always --all-files
